%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(dmsl_elastico_thrift).

-include("dmsl_elastico_thrift.hrl").

-export([namespace/0]).
-export([enums/0]).
-export([typedefs/0]).
-export([structs/0]).
-export([services/0]).
-export([typedef_info/1]).
-export([enum_info/1]).
-export([struct_info/1]).
-export([record_name/1]).
-export([functions/1]).
-export([function_info/3]).

-export_type([namespace/0]).
-export_type([typedef_name/0]).
-export_type([enum_name/0]).
-export_type([struct_name/0]).
-export_type([exception_name/0]).
-export_type([service_name/0]).
-export_type([function_name/0]).

-export_type([enum_info/0]).
-export_type([struct_info/0]).

-export_type([
    'PartyID'/0,
    'ShopID'/0
]).
-export_type([
    'PartyNotFound'/0
]).

-type namespace() :: 'elastico'.

%%
%% typedefs
%%
-type typedef_name() ::
    'PartyID' |
    'ShopID'.

-type 'PartyID'() :: dmsl_domain_thrift:'PartyID'().
-type 'ShopID'() :: dmsl_domain_thrift:'ShopID'().

%%
%% enums
%%
-type enum_name() :: none().

%%
%% structs, unions and exceptions
%%
-type struct_name() :: none().

-type exception_name() ::
    'PartyNotFound'.

%% exception 'PartyNotFound'
-type 'PartyNotFound'() :: #'elastico_PartyNotFound'{}.

%%
%% services and functions
%%
-type service_name() ::
    'Elastico'.

-type function_name() ::
    'Elastico_service_functions'().

-type 'Elastico_service_functions'() ::
    'getPartyById' |
    'searchParty'.

-export_type(['Elastico_service_functions'/0]).


-type struct_flavour() :: struct | exception | union.
-type field_num() :: pos_integer().
-type field_name() :: atom().
-type field_req() :: required | optional | undefined.

-type type_ref() :: {module(), atom()}.
-type field_type() ::
    bool | byte | i16 | i32 | i64 | string | double |
{enum, type_ref()} |
{struct, struct_flavour(), type_ref()} |
{list, field_type()} |
{set, field_type()} |
{map, field_type(), field_type()}.

-type struct_field_info() ::
    {field_num(), field_req(), field_type(), field_name(), any()}.
-type struct_info() ::
    {struct, struct_flavour(), [struct_field_info()]}.

-type enum_choice() :: none().

-type enum_field_info() ::
    {enum_choice(), integer()}.
-type enum_info() ::
    {enum, [enum_field_info()]}.

-spec typedefs() -> [typedef_name()].

typedefs() ->
    [
        'PartyID',
        'ShopID'
    ].

-spec enums() -> [].

enums() ->
    [].

-spec structs() -> [].

structs() ->
    [].

-spec services() -> [service_name()].

services() ->
    [
        'Elastico'
    ].

-spec namespace() -> namespace().

namespace() ->
    'elastico'.

-spec typedef_info(typedef_name()) -> field_type() | no_return().

typedef_info('PartyID') ->
    string;

typedef_info('ShopID') ->
    string;

typedef_info(_) -> erlang:error(badarg).

-spec enum_info(_) -> no_return().

enum_info(_) -> erlang:error(badarg).

-spec struct_info(struct_name() | exception_name()) -> struct_info() | no_return().

struct_info('PartyNotFound') ->
    {struct, exception, []};

struct_info(_) -> erlang:error(badarg).

-spec record_name(struct_name() | exception_name()) -> atom() | no_return().

record_name('PartyNotFound') ->
    'elastico_PartyNotFound';

record_name(_) -> error(badarg).
    
    -spec functions(service_name()) -> [function_name()] | no_return().

functions('Elastico') ->
    [
        'getPartyById',
        'searchParty'
    ];

functions(_) -> error(badarg).

-spec function_info(service_name(), function_name(), params_type | reply_type | exceptions) ->
    struct_info() | no_return().

function_info('Elastico', 'getPartyById', params_type) ->
    {struct, struct, [
    {1, undefined, string, 'partyId', undefined}
]};
function_info('Elastico', 'getPartyById', reply_type) ->
        {struct, struct, {dmsl_domain_thrift, 'Party'}};
    function_info('Elastico', 'getPartyById', exceptions) ->
        {struct, struct, [
        {1, undefined, {struct, exception, {dmsl_elastico_thrift, 'PartyNotFound'}}, 'ex1', undefined}
    ]};
function_info('Elastico', 'searchParty', params_type) ->
    {struct, struct, [
    {1, undefined, string, 'text', undefined}
]};
function_info('Elastico', 'searchParty', reply_type) ->
        {list, {struct, struct, {dmsl_domain_thrift, 'Party'}}};
    function_info('Elastico', 'searchParty', exceptions) ->
        {struct, struct, []};

function_info(_Service, _Function, _InfoType) -> erlang:error(badarg).
