%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(dmsl_test_thrift).

-include("dmsl_test_thrift.hrl").

-export([namespace/0]).
-export([enums/0]).
-export([typedefs/0]).
-export([structs/0]).
-export([services/0]).
-export([typedef_info/1]).
-export([enum_info/1]).
-export([struct_info/1]).
-export([record_name/1]).
-export([functions/1]).
-export([function_info/3]).

-export_type([namespace/0]).
-export_type([typedef_name/0]).
-export_type([enum_name/0]).
-export_type([struct_name/0]).
-export_type([exception_name/0]).
-export_type([service_name/0]).
-export_type([function_name/0]).

-export_type([enum_info/0]).
-export_type([struct_info/0]).

-export_type([
    'Shout'/0
]).
-export_type([
    'Failure'/0
]).

-type namespace() :: ''.

%%
%% typedefs
%%
-type typedef_name() :: none().


%%
%% enums
%%
-type enum_name() :: none().

%%
%% structs, unions and exceptions
%%
-type struct_name() ::
    'Shout'.

-type exception_name() ::
    'Failure'.

%% struct 'Shout'
-type 'Shout'() :: #'Shout'{}.

%% exception 'Failure'
-type 'Failure'() :: #'Failure'{}.

%%
%% services and functions
%%
-type service_name() ::
    'Echo'.

-type function_name() ::
    'Echo_service_functions'().

-type 'Echo_service_functions'() ::
    'echo'.

-export_type(['Echo_service_functions'/0]).


-type struct_flavour() :: struct | exception | union.
-type field_num() :: pos_integer().
-type field_name() :: atom().
-type field_req() :: required | optional | undefined.

-type type_ref() :: {module(), atom()}.
-type field_type() ::
    bool | byte | i16 | i32 | i64 | string | double |
{enum, type_ref()} |
{struct, struct_flavour(), type_ref()} |
{list, field_type()} |
{set, field_type()} |
{map, field_type(), field_type()}.

-type struct_field_info() ::
    {field_num(), field_req(), field_type(), field_name(), any()}.
-type struct_info() ::
    {struct, struct_flavour(), [struct_field_info()]}.

-type enum_choice() :: none().

-type enum_field_info() ::
    {enum_choice(), integer()}.
-type enum_info() ::
    {enum, [enum_field_info()]}.

-spec typedefs() -> [].

typedefs() ->
    [].

-spec enums() -> [].

enums() ->
    [].

-spec structs() -> [struct_name()].

structs() ->
    [
        'Shout'
    ].

-spec services() -> [service_name()].

services() ->
    [
        'Echo'
    ].

-spec namespace() -> namespace().

namespace() ->
    ''.

-spec typedef_info(_) -> no_return().

typedef_info(_) -> erlang:error(badarg).

-spec enum_info(_) -> no_return().

enum_info(_) -> erlang:error(badarg).

-spec struct_info(struct_name() | exception_name()) -> struct_info() | no_return().

struct_info('Shout') ->
    {struct, struct, [
    {1, required, string, 'contents', undefined}
]};

struct_info('Failure') ->
    {struct, exception, [
    {1, required, string, 'reason', undefined}
]};

struct_info(_) -> erlang:error(badarg).

-spec record_name(struct_name() | exception_name()) -> atom() | no_return().

record_name('Shout') ->
    'Shout';

record_name('Failure') ->
    'Failure';

    record_name(_) -> error(badarg).
    
    -spec functions(service_name()) -> [function_name()] | no_return().

functions('Echo') ->
    [
        'echo'
    ];

functions(_) -> error(badarg).

-spec function_info(service_name(), function_name(), params_type | reply_type | exceptions) ->
    struct_info() | no_return().

function_info('Echo', 'echo', params_type) ->
    {struct, struct, [
    {1, undefined, {struct, struct, {dmsl_test_thrift, 'Shout'}}, 'shout', undefined}
]};
function_info('Echo', 'echo', reply_type) ->
        {struct, struct, {dmsl_test_thrift, 'Shout'}};
    function_info('Echo', 'echo', exceptions) ->
        {struct, struct, [
        {1, undefined, {struct, exception, {dmsl_test_thrift, 'Failure'}}, 'ex', undefined}
    ]};

function_info(_Service, _Function, _InfoType) -> erlang:error(badarg).
