%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(dmsl_webhooker_thrift).

-include("dmsl_webhooker_thrift.hrl").

-export([namespace/0]).
-export([enums/0]).
-export([typedefs/0]).
-export([structs/0]).
-export([services/0]).
-export([typedef_info/1]).
-export([enum_info/1]).
-export([struct_info/1]).
-export([record_name/1]).
-export([functions/1]).
-export([function_info/3]).

-export_type([namespace/0]).
-export_type([typedef_name/0]).
-export_type([enum_name/0]).
-export_type([struct_name/0]).
-export_type([exception_name/0]).
-export_type([service_name/0]).
-export_type([function_name/0]).

-export_type([enum_info/0]).
-export_type([struct_info/0]).

-export_type([
    'Url'/0,
    'Key'/0,
    'WebhookID'/0
]).
-export_type([
    'Webhook'/0,
    'WebhookParams'/0,
    'EventFilter'/0,
    'PartyEventFilter'/0,
    'PartyEventType'/0,
    'ClaimEventType'/0,
    'ClaimCreated'/0,
    'ClaimDenied'/0,
    'ClaimAccepted'/0,
    'InvoiceEventFilter'/0,
    'InvoiceEventType'/0,
    'InvoiceCreated'/0,
    'InvoiceStatusChanged'/0,
    'InvoiceStatus'/0,
    'InvoiceUnpaid'/0,
    'InvoicePaid'/0,
    'InvoiceCancelled'/0,
    'InvoiceFulfilled'/0,
    'InvoicePaymentEventType'/0,
    'InvoicePaymentCreated'/0,
    'InvoicePaymentStatusChanged'/0,
    'InvoicePaymentRefundChange'/0,
    'InvoicePaymentRefundCreated'/0,
    'InvoicePaymentRefundStatusChanged'/0,
    'InvoicePaymentStatus'/0,
    'InvoicePaymentPending'/0,
    'InvoicePaymentProcessed'/0,
    'InvoicePaymentCaptured'/0,
    'InvoicePaymentCancelled'/0,
    'InvoicePaymentFailed'/0,
    'InvoicePaymentRefunded'/0,
    'InvoicePaymentRefundStatus'/0,
    'InvoicePaymentRefundPending'/0,
    'InvoicePaymentRefundSucceeded'/0,
    'InvoicePaymentRefundFailed'/0,
    'CustomerEventFilter'/0,
    'CustomerEventType'/0,
    'CustomerCreated'/0,
    'CustomerDeleted'/0,
    'CustomerStatusReady'/0,
    'CustomerBindingEvent'/0,
    'CustomerBindingStarted'/0,
    'CustomerBindingSucceeded'/0,
    'CustomerBindingFailed'/0
]).
-export_type([
    'WebhookNotFound'/0
]).

-type namespace() :: 'webhooker'.

%%
%% typedefs
%%
-type typedef_name() ::
    'Url' |
    'Key' |
    'WebhookID'.

-type 'Url'() :: binary().
-type 'Key'() :: binary().
-type 'WebhookID'() :: integer().

%%
%% enums
%%
-type enum_name() :: none().

%%
%% structs, unions and exceptions
%%
-type struct_name() ::
    'Webhook' |
    'WebhookParams' |
    'EventFilter' |
    'PartyEventFilter' |
    'PartyEventType' |
    'ClaimEventType' |
    'ClaimCreated' |
    'ClaimDenied' |
    'ClaimAccepted' |
    'InvoiceEventFilter' |
    'InvoiceEventType' |
    'InvoiceCreated' |
    'InvoiceStatusChanged' |
    'InvoiceStatus' |
    'InvoiceUnpaid' |
    'InvoicePaid' |
    'InvoiceCancelled' |
    'InvoiceFulfilled' |
    'InvoicePaymentEventType' |
    'InvoicePaymentCreated' |
    'InvoicePaymentStatusChanged' |
    'InvoicePaymentRefundChange' |
    'InvoicePaymentRefundCreated' |
    'InvoicePaymentRefundStatusChanged' |
    'InvoicePaymentStatus' |
    'InvoicePaymentPending' |
    'InvoicePaymentProcessed' |
    'InvoicePaymentCaptured' |
    'InvoicePaymentCancelled' |
    'InvoicePaymentFailed' |
    'InvoicePaymentRefunded' |
    'InvoicePaymentRefundStatus' |
    'InvoicePaymentRefundPending' |
    'InvoicePaymentRefundSucceeded' |
    'InvoicePaymentRefundFailed' |
    'CustomerEventFilter' |
    'CustomerEventType' |
    'CustomerCreated' |
    'CustomerDeleted' |
    'CustomerStatusReady' |
    'CustomerBindingEvent' |
    'CustomerBindingStarted' |
    'CustomerBindingSucceeded' |
    'CustomerBindingFailed'.

-type exception_name() ::
    'WebhookNotFound'.

%% struct 'Webhook'
-type 'Webhook'() :: #'webhooker_Webhook'{}.

%% struct 'WebhookParams'
-type 'WebhookParams'() :: #'webhooker_WebhookParams'{}.

%% union 'EventFilter'
-type 'EventFilter'() ::
    {'party', 'PartyEventFilter'()} |
    {'invoice', 'InvoiceEventFilter'()} |
    {'customer', 'CustomerEventFilter'()}.

%% struct 'PartyEventFilter'
-type 'PartyEventFilter'() :: #'webhooker_PartyEventFilter'{}.

%% union 'PartyEventType'
-type 'PartyEventType'() ::
    {'claim', 'ClaimEventType'()}.

%% union 'ClaimEventType'
-type 'ClaimEventType'() ::
    {'created', 'ClaimCreated'()} |
    {'denied', 'ClaimDenied'()} |
    {'accepted', 'ClaimAccepted'()}.

%% struct 'ClaimCreated'
-type 'ClaimCreated'() :: #'webhooker_ClaimCreated'{}.

%% struct 'ClaimDenied'
-type 'ClaimDenied'() :: #'webhooker_ClaimDenied'{}.

%% struct 'ClaimAccepted'
-type 'ClaimAccepted'() :: #'webhooker_ClaimAccepted'{}.

%% struct 'InvoiceEventFilter'
-type 'InvoiceEventFilter'() :: #'webhooker_InvoiceEventFilter'{}.

%% union 'InvoiceEventType'
-type 'InvoiceEventType'() ::
    {'created', 'InvoiceCreated'()} |
    {'status_changed', 'InvoiceStatusChanged'()} |
    {'payment', 'InvoicePaymentEventType'()}.

%% struct 'InvoiceCreated'
-type 'InvoiceCreated'() :: #'webhooker_InvoiceCreated'{}.

%% struct 'InvoiceStatusChanged'
-type 'InvoiceStatusChanged'() :: #'webhooker_InvoiceStatusChanged'{}.

%% union 'InvoiceStatus'
-type 'InvoiceStatus'() ::
    {'unpaid', 'InvoiceUnpaid'()} |
    {'paid', 'InvoicePaid'()} |
    {'cancelled', 'InvoiceCancelled'()} |
    {'fulfilled', 'InvoiceFulfilled'()}.

%% struct 'InvoiceUnpaid'
-type 'InvoiceUnpaid'() :: #'webhooker_InvoiceUnpaid'{}.

%% struct 'InvoicePaid'
-type 'InvoicePaid'() :: #'webhooker_InvoicePaid'{}.

%% struct 'InvoiceCancelled'
-type 'InvoiceCancelled'() :: #'webhooker_InvoiceCancelled'{}.

%% struct 'InvoiceFulfilled'
-type 'InvoiceFulfilled'() :: #'webhooker_InvoiceFulfilled'{}.

%% union 'InvoicePaymentEventType'
-type 'InvoicePaymentEventType'() ::
    {'created', 'InvoicePaymentCreated'()} |
    {'status_changed', 'InvoicePaymentStatusChanged'()} |
    {'invoice_payment_refund_change', 'InvoicePaymentRefundChange'()}.

%% struct 'InvoicePaymentCreated'
-type 'InvoicePaymentCreated'() :: #'webhooker_InvoicePaymentCreated'{}.

%% struct 'InvoicePaymentStatusChanged'
-type 'InvoicePaymentStatusChanged'() :: #'webhooker_InvoicePaymentStatusChanged'{}.

%% struct 'InvoicePaymentRefundChange'
-type 'InvoicePaymentRefundChange'() :: #'webhooker_InvoicePaymentRefundChange'{}.

%% struct 'InvoicePaymentRefundCreated'
-type 'InvoicePaymentRefundCreated'() :: #'webhooker_InvoicePaymentRefundCreated'{}.

%% struct 'InvoicePaymentRefundStatusChanged'
-type 'InvoicePaymentRefundStatusChanged'() :: #'webhooker_InvoicePaymentRefundStatusChanged'{}.

%% union 'InvoicePaymentStatus'
-type 'InvoicePaymentStatus'() ::
    {'pending', 'InvoicePaymentPending'()} |
    {'processed', 'InvoicePaymentProcessed'()} |
    {'captured', 'InvoicePaymentCaptured'()} |
    {'cancelled', 'InvoicePaymentCancelled'()} |
    {'failed', 'InvoicePaymentFailed'()} |
    {'refunded', 'InvoicePaymentRefunded'()}.

%% struct 'InvoicePaymentPending'
-type 'InvoicePaymentPending'() :: #'webhooker_InvoicePaymentPending'{}.

%% struct 'InvoicePaymentProcessed'
-type 'InvoicePaymentProcessed'() :: #'webhooker_InvoicePaymentProcessed'{}.

%% struct 'InvoicePaymentCaptured'
-type 'InvoicePaymentCaptured'() :: #'webhooker_InvoicePaymentCaptured'{}.

%% struct 'InvoicePaymentCancelled'
-type 'InvoicePaymentCancelled'() :: #'webhooker_InvoicePaymentCancelled'{}.

%% struct 'InvoicePaymentFailed'
-type 'InvoicePaymentFailed'() :: #'webhooker_InvoicePaymentFailed'{}.

%% struct 'InvoicePaymentRefunded'
-type 'InvoicePaymentRefunded'() :: #'webhooker_InvoicePaymentRefunded'{}.

%% union 'InvoicePaymentRefundStatus'
-type 'InvoicePaymentRefundStatus'() ::
    {'pending', 'InvoicePaymentRefundPending'()} |
    {'succeeded', 'InvoicePaymentRefundSucceeded'()} |
    {'failed', 'InvoicePaymentRefundFailed'()}.

%% struct 'InvoicePaymentRefundPending'
-type 'InvoicePaymentRefundPending'() :: #'webhooker_InvoicePaymentRefundPending'{}.

%% struct 'InvoicePaymentRefundSucceeded'
-type 'InvoicePaymentRefundSucceeded'() :: #'webhooker_InvoicePaymentRefundSucceeded'{}.

%% struct 'InvoicePaymentRefundFailed'
-type 'InvoicePaymentRefundFailed'() :: #'webhooker_InvoicePaymentRefundFailed'{}.

%% struct 'CustomerEventFilter'
-type 'CustomerEventFilter'() :: #'webhooker_CustomerEventFilter'{}.

%% union 'CustomerEventType'
-type 'CustomerEventType'() ::
    {'created', 'CustomerCreated'()} |
    {'deleted', 'CustomerDeleted'()} |
    {'ready', 'CustomerStatusReady'()} |
    {'binding', 'CustomerBindingEvent'()}.

%% struct 'CustomerCreated'
-type 'CustomerCreated'() :: #'webhooker_CustomerCreated'{}.

%% struct 'CustomerDeleted'
-type 'CustomerDeleted'() :: #'webhooker_CustomerDeleted'{}.

%% struct 'CustomerStatusReady'
-type 'CustomerStatusReady'() :: #'webhooker_CustomerStatusReady'{}.

%% union 'CustomerBindingEvent'
-type 'CustomerBindingEvent'() ::
    {'started', 'CustomerBindingStarted'()} |
    {'succeeded', 'CustomerBindingSucceeded'()} |
    {'failed', 'CustomerBindingFailed'()}.

%% struct 'CustomerBindingStarted'
-type 'CustomerBindingStarted'() :: #'webhooker_CustomerBindingStarted'{}.

%% struct 'CustomerBindingSucceeded'
-type 'CustomerBindingSucceeded'() :: #'webhooker_CustomerBindingSucceeded'{}.

%% struct 'CustomerBindingFailed'
-type 'CustomerBindingFailed'() :: #'webhooker_CustomerBindingFailed'{}.

%% exception 'WebhookNotFound'
-type 'WebhookNotFound'() :: #'webhooker_WebhookNotFound'{}.

%%
%% services and functions
%%
-type service_name() ::
    'WebhookManager'.

-type function_name() ::
    'WebhookManager_service_functions'().

-type 'WebhookManager_service_functions'() ::
    'GetList' |
    'Get' |
    'Create' |
    'Delete'.

-export_type(['WebhookManager_service_functions'/0]).


-type struct_flavour() :: struct | exception | union.
-type field_num() :: pos_integer().
-type field_name() :: atom().
-type field_req() :: required | optional | undefined.

-type type_ref() :: {module(), atom()}.
-type field_type() ::
    bool | byte | i16 | i32 | i64 | string | double |
{enum, type_ref()} |
{struct, struct_flavour(), type_ref()} |
{list, field_type()} |
{set, field_type()} |
{map, field_type(), field_type()}.

-type struct_field_info() ::
    {field_num(), field_req(), field_type(), field_name(), any()}.
-type struct_info() ::
    {struct, struct_flavour(), [struct_field_info()]}.

-type enum_choice() :: none().

-type enum_field_info() ::
    {enum_choice(), integer()}.
-type enum_info() ::
    {enum, [enum_field_info()]}.

-spec typedefs() -> [typedef_name()].

typedefs() ->
    [
        'Url',
        'Key',
        'WebhookID'
    ].

-spec enums() -> [].

enums() ->
    [].

-spec structs() -> [struct_name()].

structs() ->
    [
        'Webhook',
        'WebhookParams',
        'EventFilter',
        'PartyEventFilter',
        'PartyEventType',
        'ClaimEventType',
        'ClaimCreated',
        'ClaimDenied',
        'ClaimAccepted',
        'InvoiceEventFilter',
        'InvoiceEventType',
        'InvoiceCreated',
        'InvoiceStatusChanged',
        'InvoiceStatus',
        'InvoiceUnpaid',
        'InvoicePaid',
        'InvoiceCancelled',
        'InvoiceFulfilled',
        'InvoicePaymentEventType',
        'InvoicePaymentCreated',
        'InvoicePaymentStatusChanged',
        'InvoicePaymentRefundChange',
        'InvoicePaymentRefundCreated',
        'InvoicePaymentRefundStatusChanged',
        'InvoicePaymentStatus',
        'InvoicePaymentPending',
        'InvoicePaymentProcessed',
        'InvoicePaymentCaptured',
        'InvoicePaymentCancelled',
        'InvoicePaymentFailed',
        'InvoicePaymentRefunded',
        'InvoicePaymentRefundStatus',
        'InvoicePaymentRefundPending',
        'InvoicePaymentRefundSucceeded',
        'InvoicePaymentRefundFailed',
        'CustomerEventFilter',
        'CustomerEventType',
        'CustomerCreated',
        'CustomerDeleted',
        'CustomerStatusReady',
        'CustomerBindingEvent',
        'CustomerBindingStarted',
        'CustomerBindingSucceeded',
        'CustomerBindingFailed'
    ].

-spec services() -> [service_name()].

services() ->
    [
        'WebhookManager'
    ].

-spec namespace() -> namespace().

namespace() ->
    'webhooker'.

-spec typedef_info(typedef_name()) -> field_type() | no_return().

typedef_info('Url') ->
    string;

typedef_info('Key') ->
    string;

typedef_info('WebhookID') ->
    i64;

typedef_info(_) -> erlang:error(badarg).

-spec enum_info(_) -> no_return().

enum_info(_) -> erlang:error(badarg).

-spec struct_info(struct_name() | exception_name()) -> struct_info() | no_return().

struct_info('Webhook') ->
    {struct, struct, [
    {1, required, i64, 'id', undefined},
    {2, required, string, 'party_id', undefined},
    {3, required, {struct, union, {dmsl_webhooker_thrift, 'EventFilter'}}, 'event_filter', undefined},
    {4, required, string, 'url', undefined},
    {5, required, string, 'pub_key', undefined},
    {6, required, bool, 'enabled', undefined}
]};

struct_info('WebhookParams') ->
    {struct, struct, [
    {1, required, string, 'party_id', undefined},
    {2, required, {struct, union, {dmsl_webhooker_thrift, 'EventFilter'}}, 'event_filter', undefined},
    {3, required, string, 'url', undefined}
]};

struct_info('EventFilter') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_webhooker_thrift, 'PartyEventFilter'}}, 'party', undefined},
    {2, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoiceEventFilter'}}, 'invoice', undefined},
    {3, optional, {struct, struct, {dmsl_webhooker_thrift, 'CustomerEventFilter'}}, 'customer', undefined}
]};

struct_info('PartyEventFilter') ->
    {struct, struct, [
    {1, required, {set, {struct, union, {dmsl_webhooker_thrift, 'PartyEventType'}}}, 'types', undefined}
]};

struct_info('PartyEventType') ->
    {struct, union, [
    {1, optional, {struct, union, {dmsl_webhooker_thrift, 'ClaimEventType'}}, 'claim', undefined}
]};

struct_info('ClaimEventType') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_webhooker_thrift, 'ClaimCreated'}}, 'created', undefined},
    {2, optional, {struct, struct, {dmsl_webhooker_thrift, 'ClaimDenied'}}, 'denied', undefined},
    {3, optional, {struct, struct, {dmsl_webhooker_thrift, 'ClaimAccepted'}}, 'accepted', undefined}
]};

struct_info('ClaimCreated') ->
    {struct, struct, []};

struct_info('ClaimDenied') ->
    {struct, struct, []};

struct_info('ClaimAccepted') ->
    {struct, struct, []};

struct_info('InvoiceEventFilter') ->
    {struct, struct, [
    {1, required, {set, {struct, union, {dmsl_webhooker_thrift, 'InvoiceEventType'}}}, 'types', undefined},
    {2, optional, string, 'shop_id', undefined}
]};

struct_info('InvoiceEventType') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoiceCreated'}}, 'created', undefined},
    {2, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoiceStatusChanged'}}, 'status_changed', undefined},
    {3, optional, {struct, union, {dmsl_webhooker_thrift, 'InvoicePaymentEventType'}}, 'payment', undefined}
]};

struct_info('InvoiceCreated') ->
    {struct, struct, []};

struct_info('InvoiceStatusChanged') ->
    {struct, struct, [
    {1, optional, {struct, union, {dmsl_webhooker_thrift, 'InvoiceStatus'}}, 'value', undefined}
]};

struct_info('InvoiceStatus') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoiceUnpaid'}}, 'unpaid', undefined},
    {2, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaid'}}, 'paid', undefined},
    {3, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoiceCancelled'}}, 'cancelled', undefined},
    {4, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoiceFulfilled'}}, 'fulfilled', undefined}
]};

struct_info('InvoiceUnpaid') ->
    {struct, struct, []};

struct_info('InvoicePaid') ->
    {struct, struct, []};

struct_info('InvoiceCancelled') ->
    {struct, struct, []};

struct_info('InvoiceFulfilled') ->
    {struct, struct, []};

struct_info('InvoicePaymentEventType') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentCreated'}}, 'created', undefined},
    {2, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentStatusChanged'}}, 'status_changed', undefined},
    {3, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentRefundChange'}}, 'invoice_payment_refund_change', undefined}
]};

struct_info('InvoicePaymentCreated') ->
    {struct, struct, []};

struct_info('InvoicePaymentStatusChanged') ->
    {struct, struct, [
    {1, optional, {struct, union, {dmsl_webhooker_thrift, 'InvoicePaymentStatus'}}, 'value', undefined}
]};

struct_info('InvoicePaymentRefundChange') ->
    {struct, struct, [
    {1, undefined, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentRefundCreated'}}, 'invoice_payment_refund_created', undefined},
    {2, undefined, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentRefundStatusChanged'}}, 'invoice_payment_refund_status_changed', undefined}
]};

struct_info('InvoicePaymentRefundCreated') ->
    {struct, struct, []};

struct_info('InvoicePaymentRefundStatusChanged') ->
    {struct, struct, [
    {1, required, {struct, union, {dmsl_webhooker_thrift, 'InvoicePaymentRefundStatus'}}, 'value', undefined}
]};

struct_info('InvoicePaymentStatus') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentPending'}}, 'pending', undefined},
    {4, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentProcessed'}}, 'processed', undefined},
    {2, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentCaptured'}}, 'captured', undefined},
    {5, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentCancelled'}}, 'cancelled', undefined},
    {3, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentFailed'}}, 'failed', undefined},
    {6, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentRefunded'}}, 'refunded', undefined}
]};

struct_info('InvoicePaymentPending') ->
    {struct, struct, []};

struct_info('InvoicePaymentProcessed') ->
    {struct, struct, []};

struct_info('InvoicePaymentCaptured') ->
    {struct, struct, []};

struct_info('InvoicePaymentCancelled') ->
    {struct, struct, []};

struct_info('InvoicePaymentFailed') ->
    {struct, struct, []};

struct_info('InvoicePaymentRefunded') ->
    {struct, struct, []};

struct_info('InvoicePaymentRefundStatus') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentRefundPending'}}, 'pending', undefined},
    {2, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentRefundSucceeded'}}, 'succeeded', undefined},
    {3, optional, {struct, struct, {dmsl_webhooker_thrift, 'InvoicePaymentRefundFailed'}}, 'failed', undefined}
]};

struct_info('InvoicePaymentRefundPending') ->
    {struct, struct, []};

struct_info('InvoicePaymentRefundSucceeded') ->
    {struct, struct, []};

struct_info('InvoicePaymentRefundFailed') ->
    {struct, struct, []};

struct_info('CustomerEventFilter') ->
    {struct, struct, [
    {1, required, {set, {struct, union, {dmsl_webhooker_thrift, 'CustomerEventType'}}}, 'types', undefined},
    {2, optional, string, 'shop_id', undefined}
]};

struct_info('CustomerEventType') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_webhooker_thrift, 'CustomerCreated'}}, 'created', undefined},
    {2, optional, {struct, struct, {dmsl_webhooker_thrift, 'CustomerDeleted'}}, 'deleted', undefined},
    {3, optional, {struct, struct, {dmsl_webhooker_thrift, 'CustomerStatusReady'}}, 'ready', undefined},
    {4, optional, {struct, union, {dmsl_webhooker_thrift, 'CustomerBindingEvent'}}, 'binding', undefined}
]};

struct_info('CustomerCreated') ->
    {struct, struct, []};

struct_info('CustomerDeleted') ->
    {struct, struct, []};

struct_info('CustomerStatusReady') ->
    {struct, struct, []};

struct_info('CustomerBindingEvent') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_webhooker_thrift, 'CustomerBindingStarted'}}, 'started', undefined},
    {2, optional, {struct, struct, {dmsl_webhooker_thrift, 'CustomerBindingSucceeded'}}, 'succeeded', undefined},
    {3, optional, {struct, struct, {dmsl_webhooker_thrift, 'CustomerBindingFailed'}}, 'failed', undefined}
]};

struct_info('CustomerBindingStarted') ->
    {struct, struct, []};

struct_info('CustomerBindingSucceeded') ->
    {struct, struct, []};

struct_info('CustomerBindingFailed') ->
    {struct, struct, []};

struct_info('WebhookNotFound') ->
    {struct, exception, []};

struct_info(_) -> erlang:error(badarg).

-spec record_name(struct_name() | exception_name()) -> atom() | no_return().

record_name('Webhook') ->
    'webhooker_Webhook';

record_name('WebhookParams') ->
    'webhooker_WebhookParams';

    record_name('PartyEventFilter') ->
    'webhooker_PartyEventFilter';

    record_name('ClaimCreated') ->
    'webhooker_ClaimCreated';

    record_name('ClaimDenied') ->
    'webhooker_ClaimDenied';

    record_name('ClaimAccepted') ->
    'webhooker_ClaimAccepted';

    record_name('InvoiceEventFilter') ->
    'webhooker_InvoiceEventFilter';

    record_name('InvoiceCreated') ->
    'webhooker_InvoiceCreated';

    record_name('InvoiceStatusChanged') ->
    'webhooker_InvoiceStatusChanged';

    record_name('InvoiceUnpaid') ->
    'webhooker_InvoiceUnpaid';

    record_name('InvoicePaid') ->
    'webhooker_InvoicePaid';

    record_name('InvoiceCancelled') ->
    'webhooker_InvoiceCancelled';

    record_name('InvoiceFulfilled') ->
    'webhooker_InvoiceFulfilled';

    record_name('InvoicePaymentCreated') ->
    'webhooker_InvoicePaymentCreated';

    record_name('InvoicePaymentStatusChanged') ->
    'webhooker_InvoicePaymentStatusChanged';

    record_name('InvoicePaymentRefundChange') ->
    'webhooker_InvoicePaymentRefundChange';

    record_name('InvoicePaymentRefundCreated') ->
    'webhooker_InvoicePaymentRefundCreated';

    record_name('InvoicePaymentRefundStatusChanged') ->
    'webhooker_InvoicePaymentRefundStatusChanged';

    record_name('InvoicePaymentPending') ->
    'webhooker_InvoicePaymentPending';

    record_name('InvoicePaymentProcessed') ->
    'webhooker_InvoicePaymentProcessed';

    record_name('InvoicePaymentCaptured') ->
    'webhooker_InvoicePaymentCaptured';

    record_name('InvoicePaymentCancelled') ->
    'webhooker_InvoicePaymentCancelled';

    record_name('InvoicePaymentFailed') ->
    'webhooker_InvoicePaymentFailed';

    record_name('InvoicePaymentRefunded') ->
    'webhooker_InvoicePaymentRefunded';

    record_name('InvoicePaymentRefundPending') ->
    'webhooker_InvoicePaymentRefundPending';

    record_name('InvoicePaymentRefundSucceeded') ->
    'webhooker_InvoicePaymentRefundSucceeded';

    record_name('InvoicePaymentRefundFailed') ->
    'webhooker_InvoicePaymentRefundFailed';

    record_name('CustomerEventFilter') ->
    'webhooker_CustomerEventFilter';

    record_name('CustomerCreated') ->
    'webhooker_CustomerCreated';

    record_name('CustomerDeleted') ->
    'webhooker_CustomerDeleted';

    record_name('CustomerStatusReady') ->
    'webhooker_CustomerStatusReady';

    record_name('CustomerBindingStarted') ->
    'webhooker_CustomerBindingStarted';

    record_name('CustomerBindingSucceeded') ->
    'webhooker_CustomerBindingSucceeded';

    record_name('CustomerBindingFailed') ->
    'webhooker_CustomerBindingFailed';

    record_name('WebhookNotFound') ->
    'webhooker_WebhookNotFound';

    record_name(_) -> error(badarg).
    
    -spec functions(service_name()) -> [function_name()] | no_return().

functions('WebhookManager') ->
    [
        'GetList',
        'Get',
        'Create',
        'Delete'
    ];

functions(_) -> error(badarg).

-spec function_info(service_name(), function_name(), params_type | reply_type | exceptions) ->
    struct_info() | no_return().

function_info('WebhookManager', 'GetList', params_type) ->
    {struct, struct, [
    {1, undefined, string, 'party_id', undefined}
]};
function_info('WebhookManager', 'GetList', reply_type) ->
        {list, {struct, struct, {dmsl_webhooker_thrift, 'Webhook'}}};
    function_info('WebhookManager', 'GetList', exceptions) ->
        {struct, struct, []};
function_info('WebhookManager', 'Get', params_type) ->
    {struct, struct, [
    {1, undefined, i64, 'webhook_id', undefined}
]};
function_info('WebhookManager', 'Get', reply_type) ->
        {struct, struct, {dmsl_webhooker_thrift, 'Webhook'}};
    function_info('WebhookManager', 'Get', exceptions) ->
        {struct, struct, [
        {1, undefined, {struct, exception, {dmsl_webhooker_thrift, 'WebhookNotFound'}}, 'ex1', undefined}
    ]};
function_info('WebhookManager', 'Create', params_type) ->
    {struct, struct, [
    {1, undefined, {struct, struct, {dmsl_webhooker_thrift, 'WebhookParams'}}, 'webhook_params', undefined}
]};
function_info('WebhookManager', 'Create', reply_type) ->
        {struct, struct, {dmsl_webhooker_thrift, 'Webhook'}};
    function_info('WebhookManager', 'Create', exceptions) ->
        {struct, struct, []};
function_info('WebhookManager', 'Delete', params_type) ->
    {struct, struct, [
    {1, undefined, i64, 'webhook_id', undefined}
]};
function_info('WebhookManager', 'Delete', reply_type) ->
        {struct, struct, []};
    function_info('WebhookManager', 'Delete', exceptions) ->
        {struct, struct, [
        {1, undefined, {struct, exception, {dmsl_webhooker_thrift, 'WebhookNotFound'}}, 'ex1', undefined}
    ]};

function_info(_Service, _Function, _InfoType) -> erlang:error(badarg).
