%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(dmsl_errors_thrift).

-include("dmsl_errors_thrift.hrl").

-export([namespace/0]).
-export([enums/0]).
-export([typedefs/0]).
-export([structs/0]).
-export([services/0]).
-export([typedef_info/1]).
-export([enum_info/1]).
-export([struct_info/1]).
-export([record_name/1]).
-export([functions/1]).
-export([function_info/3]).

-export_type([namespace/0]).
-export_type([typedef_name/0]).
-export_type([enum_name/0]).
-export_type([struct_name/0]).
-export_type([exception_name/0]).
-export_type([service_name/0]).
-export_type([function_name/0]).

-export_type([enum_info/0]).
-export_type([struct_info/0]).

-export_type([
    'PaymentError'/0,
    'RejectedByInspector'/0,
    'PreauthorizationError'/0,
    'AuthorizationFailed'/0,
    'SilentReject'/0,
    'MerchantBlocked'/0,
    'OperationDisabled'/0,
    'AccountNotFound'/0,
    'AccountBlocked'/0,
    'AccountStolen'/0,
    'InsufficientFunds'/0,
    'LimitExceeded'/0,
    'SingleOperationLimitExceeded'/0,
    'DailyLimitExceeded'/0,
    'WeeklyLimitExceeded'/0,
    'MonthlyLimitExceeded'/0,
    'AttemptsNumberLimitExceeded'/0,
    'PaymentToolError'/0,
    'BankCardError'/0,
    'InvalidCardNumber'/0,
    'ExpiredCard'/0,
    'InvalidCardHolder'/0,
    'InvalidCVV'/0,
    'CardNotSupported'/0,
    'IssuerNotFound'/0,
    'RestictedCard'/0
]).

-type namespace() :: ''.

%%
%% typedefs
%%
-type typedef_name() :: none().


%%
%% enums
%%
-type enum_name() :: none().

%%
%% structs, unions and exceptions
%%
-type struct_name() ::
    'PaymentError' |
    'RejectedByInspector' |
    'PreauthorizationError' |
    'AuthorizationFailed' |
    'SilentReject' |
    'MerchantBlocked' |
    'OperationDisabled' |
    'AccountNotFound' |
    'AccountBlocked' |
    'AccountStolen' |
    'InsufficientFunds' |
    'LimitExceeded' |
    'SingleOperationLimitExceeded' |
    'DailyLimitExceeded' |
    'WeeklyLimitExceeded' |
    'MonthlyLimitExceeded' |
    'AttemptsNumberLimitExceeded' |
    'PaymentToolError' |
    'BankCardError' |
    'InvalidCardNumber' |
    'ExpiredCard' |
    'InvalidCardHolder' |
    'InvalidCVV' |
    'CardNotSupported' |
    'IssuerNotFound' |
    'RestictedCard'.

-type exception_name() :: none().

%% union 'PaymentError'
-type 'PaymentError'() ::
    {'rejected_by_inspector', 'RejectedByInspector'()} |
    {'preauthorization_error', 'PreauthorizationError'()} |
    {'authorization_failed', 'AuthorizationFailed'()}.

%% struct 'RejectedByInspector'
-type 'RejectedByInspector'() :: #'RejectedByInspector'{}.

%% struct 'PreauthorizationError'
-type 'PreauthorizationError'() :: #'PreauthorizationError'{}.

%% union 'AuthorizationFailed'
-type 'AuthorizationFailed'() ::
    {'silent_reject', 'SilentReject'()} |
    {'merchant_blocked', 'MerchantBlocked'()} |
    {'operation_disabled', 'OperationDisabled'()} |
    {'account_not_found', 'AccountNotFound'()} |
    {'account_blocked', 'AccountBlocked'()} |
    {'account_stolen', 'AccountStolen'()} |
    {'insufficient_funds', 'InsufficientFunds'()} |
    {'limit_exceeded', 'LimitExceeded'()} |
    {'payment_tool_error', 'PaymentToolError'()}.

%% struct 'SilentReject'
-type 'SilentReject'() :: #'SilentReject'{}.

%% struct 'MerchantBlocked'
-type 'MerchantBlocked'() :: #'MerchantBlocked'{}.

%% struct 'OperationDisabled'
-type 'OperationDisabled'() :: #'OperationDisabled'{}.

%% struct 'AccountNotFound'
-type 'AccountNotFound'() :: #'AccountNotFound'{}.

%% struct 'AccountBlocked'
-type 'AccountBlocked'() :: #'AccountBlocked'{}.

%% struct 'AccountStolen'
-type 'AccountStolen'() :: #'AccountStolen'{}.

%% struct 'InsufficientFunds'
-type 'InsufficientFunds'() :: #'InsufficientFunds'{}.

%% union 'LimitExceeded'
-type 'LimitExceeded'() ::
    {'single_operation_limit_exceeded', 'SingleOperationLimitExceeded'()} |
    {'daily_limit_exceeded', 'DailyLimitExceeded'()} |
    {'weekly_limit_exceeded', 'WeeklyLimitExceeded'()} |
    {'monthly_limit_exceeded', 'MonthlyLimitExceeded'()} |
    {'attempts_number_exceeded', 'AttemptsNumberLimitExceeded'()}.

%% struct 'SingleOperationLimitExceeded'
-type 'SingleOperationLimitExceeded'() :: #'SingleOperationLimitExceeded'{}.

%% struct 'DailyLimitExceeded'
-type 'DailyLimitExceeded'() :: #'DailyLimitExceeded'{}.

%% struct 'WeeklyLimitExceeded'
-type 'WeeklyLimitExceeded'() :: #'WeeklyLimitExceeded'{}.

%% struct 'MonthlyLimitExceeded'
-type 'MonthlyLimitExceeded'() :: #'MonthlyLimitExceeded'{}.

%% struct 'AttemptsNumberLimitExceeded'
-type 'AttemptsNumberLimitExceeded'() :: #'AttemptsNumberLimitExceeded'{}.

%% union 'PaymentToolError'
-type 'PaymentToolError'() ::
    {'bank_card_error', 'BankCardError'()}.

%% union 'BankCardError'
-type 'BankCardError'() ::
    {'invalid_card_number', 'InvalidCardNumber'()} |
    {'expired_card', 'ExpiredCard'()} |
    {'invalid_card_holder', 'InvalidCardHolder'()} |
    {'invalid_cvv', 'InvalidCVV'()} |
    {'card_not_supported', 'CardNotSupported'()} |
    {'issuer_not_found', 'IssuerNotFound'()} |
    {'resticted_card', 'RestictedCard'()}.

%% struct 'InvalidCardNumber'
-type 'InvalidCardNumber'() :: #'InvalidCardNumber'{}.

%% struct 'ExpiredCard'
-type 'ExpiredCard'() :: #'ExpiredCard'{}.

%% struct 'InvalidCardHolder'
-type 'InvalidCardHolder'() :: #'InvalidCardHolder'{}.

%% struct 'InvalidCVV'
-type 'InvalidCVV'() :: #'InvalidCVV'{}.

%% struct 'CardNotSupported'
-type 'CardNotSupported'() :: #'CardNotSupported'{}.

%% struct 'IssuerNotFound'
-type 'IssuerNotFound'() :: #'IssuerNotFound'{}.

%% struct 'RestictedCard'
-type 'RestictedCard'() :: #'RestictedCard'{}.

%%
%% services and functions
%%
-type service_name() :: none().

-type function_name() :: none().


-type struct_flavour() :: struct | exception | union.
-type field_num() :: pos_integer().
-type field_name() :: atom().
-type field_req() :: required | optional | undefined.

-type type_ref() :: {module(), atom()}.
-type field_type() ::
    bool | byte | i16 | i32 | i64 | string | double |
{enum, type_ref()} |
{struct, struct_flavour(), type_ref()} |
{list, field_type()} |
{set, field_type()} |
{map, field_type(), field_type()}.

-type struct_field_info() ::
    {field_num(), field_req(), field_type(), field_name(), any()}.
-type struct_info() ::
    {struct, struct_flavour(), [struct_field_info()]}.

-type enum_choice() :: none().

-type enum_field_info() ::
    {enum_choice(), integer()}.
-type enum_info() ::
    {enum, [enum_field_info()]}.

-spec typedefs() -> [].

typedefs() ->
    [].

-spec enums() -> [].

enums() ->
    [].

-spec structs() -> [struct_name()].

structs() ->
    [
        'PaymentError',
        'RejectedByInspector',
        'PreauthorizationError',
        'AuthorizationFailed',
        'SilentReject',
        'MerchantBlocked',
        'OperationDisabled',
        'AccountNotFound',
        'AccountBlocked',
        'AccountStolen',
        'InsufficientFunds',
        'LimitExceeded',
        'SingleOperationLimitExceeded',
        'DailyLimitExceeded',
        'WeeklyLimitExceeded',
        'MonthlyLimitExceeded',
        'AttemptsNumberLimitExceeded',
        'PaymentToolError',
        'BankCardError',
        'InvalidCardNumber',
        'ExpiredCard',
        'InvalidCardHolder',
        'InvalidCVV',
        'CardNotSupported',
        'IssuerNotFound',
        'RestictedCard'
    ].

-spec services() -> [].

services() ->
    [].

-spec namespace() -> namespace().

namespace() ->
    ''.

-spec typedef_info(_) -> no_return().

typedef_info(_) -> erlang:error(badarg).

-spec enum_info(_) -> no_return().

enum_info(_) -> erlang:error(badarg).

-spec struct_info(struct_name() | exception_name()) -> struct_info() | no_return().

struct_info('PaymentError') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_errors_thrift, 'RejectedByInspector'}}, 'rejected_by_inspector', undefined},
    {2, optional, {struct, struct, {dmsl_errors_thrift, 'PreauthorizationError'}}, 'preauthorization_error', undefined},
    {3, optional, {struct, union, {dmsl_errors_thrift, 'AuthorizationFailed'}}, 'authorization_failed', undefined}
]};

struct_info('RejectedByInspector') ->
    {struct, struct, []};

struct_info('PreauthorizationError') ->
    {struct, struct, []};

struct_info('AuthorizationFailed') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_errors_thrift, 'SilentReject'}}, 'silent_reject', undefined},
    {2, optional, {struct, struct, {dmsl_errors_thrift, 'MerchantBlocked'}}, 'merchant_blocked', undefined},
    {3, optional, {struct, struct, {dmsl_errors_thrift, 'OperationDisabled'}}, 'operation_disabled', undefined},
    {4, optional, {struct, struct, {dmsl_errors_thrift, 'AccountNotFound'}}, 'account_not_found', undefined},
    {5, optional, {struct, struct, {dmsl_errors_thrift, 'AccountBlocked'}}, 'account_blocked', undefined},
    {6, optional, {struct, struct, {dmsl_errors_thrift, 'AccountStolen'}}, 'account_stolen', undefined},
    {7, optional, {struct, struct, {dmsl_errors_thrift, 'InsufficientFunds'}}, 'insufficient_funds', undefined},
    {8, optional, {struct, union, {dmsl_errors_thrift, 'LimitExceeded'}}, 'limit_exceeded', undefined},
    {9, optional, {struct, union, {dmsl_errors_thrift, 'PaymentToolError'}}, 'payment_tool_error', undefined}
]};

struct_info('SilentReject') ->
    {struct, struct, []};

struct_info('MerchantBlocked') ->
    {struct, struct, []};

struct_info('OperationDisabled') ->
    {struct, struct, []};

struct_info('AccountNotFound') ->
    {struct, struct, []};

struct_info('AccountBlocked') ->
    {struct, struct, []};

struct_info('AccountStolen') ->
    {struct, struct, []};

struct_info('InsufficientFunds') ->
    {struct, struct, []};

struct_info('LimitExceeded') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_errors_thrift, 'SingleOperationLimitExceeded'}}, 'single_operation_limit_exceeded', undefined},
    {2, optional, {struct, struct, {dmsl_errors_thrift, 'DailyLimitExceeded'}}, 'daily_limit_exceeded', undefined},
    {3, optional, {struct, struct, {dmsl_errors_thrift, 'WeeklyLimitExceeded'}}, 'weekly_limit_exceeded', undefined},
    {4, optional, {struct, struct, {dmsl_errors_thrift, 'MonthlyLimitExceeded'}}, 'monthly_limit_exceeded', undefined},
    {5, optional, {struct, struct, {dmsl_errors_thrift, 'AttemptsNumberLimitExceeded'}}, 'attempts_number_exceeded', undefined}
]};

struct_info('SingleOperationLimitExceeded') ->
    {struct, struct, []};

struct_info('DailyLimitExceeded') ->
    {struct, struct, []};

struct_info('WeeklyLimitExceeded') ->
    {struct, struct, []};

struct_info('MonthlyLimitExceeded') ->
    {struct, struct, []};

struct_info('AttemptsNumberLimitExceeded') ->
    {struct, struct, []};

struct_info('PaymentToolError') ->
    {struct, union, [
    {1, optional, {struct, union, {dmsl_errors_thrift, 'BankCardError'}}, 'bank_card_error', undefined}
]};

struct_info('BankCardError') ->
    {struct, union, [
    {1, optional, {struct, struct, {dmsl_errors_thrift, 'InvalidCardNumber'}}, 'invalid_card_number', undefined},
    {2, optional, {struct, struct, {dmsl_errors_thrift, 'ExpiredCard'}}, 'expired_card', undefined},
    {3, optional, {struct, struct, {dmsl_errors_thrift, 'InvalidCardHolder'}}, 'invalid_card_holder', undefined},
    {4, optional, {struct, struct, {dmsl_errors_thrift, 'InvalidCVV'}}, 'invalid_cvv', undefined},
    {5, optional, {struct, struct, {dmsl_errors_thrift, 'CardNotSupported'}}, 'card_not_supported', undefined},
    {6, optional, {struct, struct, {dmsl_errors_thrift, 'IssuerNotFound'}}, 'issuer_not_found', undefined},
    {7, optional, {struct, struct, {dmsl_errors_thrift, 'RestictedCard'}}, 'resticted_card', undefined}
]};

struct_info('InvalidCardNumber') ->
    {struct, struct, []};

struct_info('ExpiredCard') ->
    {struct, struct, []};

struct_info('InvalidCardHolder') ->
    {struct, struct, []};

struct_info('InvalidCVV') ->
    {struct, struct, []};

struct_info('CardNotSupported') ->
    {struct, struct, []};

struct_info('IssuerNotFound') ->
    {struct, struct, []};

struct_info('RestictedCard') ->
    {struct, struct, []};

struct_info(_) -> erlang:error(badarg).

-spec record_name(struct_name() | exception_name()) -> atom() | no_return().

record_name('RejectedByInspector') ->
    'RejectedByInspector';

record_name('PreauthorizationError') ->
    'PreauthorizationError';

    record_name('SilentReject') ->
    'SilentReject';

    record_name('MerchantBlocked') ->
    'MerchantBlocked';

    record_name('OperationDisabled') ->
    'OperationDisabled';

    record_name('AccountNotFound') ->
    'AccountNotFound';

    record_name('AccountBlocked') ->
    'AccountBlocked';

    record_name('AccountStolen') ->
    'AccountStolen';

    record_name('InsufficientFunds') ->
    'InsufficientFunds';

    record_name('SingleOperationLimitExceeded') ->
    'SingleOperationLimitExceeded';

    record_name('DailyLimitExceeded') ->
    'DailyLimitExceeded';

    record_name('WeeklyLimitExceeded') ->
    'WeeklyLimitExceeded';

    record_name('MonthlyLimitExceeded') ->
    'MonthlyLimitExceeded';

    record_name('AttemptsNumberLimitExceeded') ->
    'AttemptsNumberLimitExceeded';

    record_name('InvalidCardNumber') ->
    'InvalidCardNumber';

    record_name('ExpiredCard') ->
    'ExpiredCard';

    record_name('InvalidCardHolder') ->
    'InvalidCardHolder';

    record_name('InvalidCVV') ->
    'InvalidCVV';

    record_name('CardNotSupported') ->
    'CardNotSupported';

    record_name('IssuerNotFound') ->
    'IssuerNotFound';

    record_name('RestictedCard') ->
    'RestictedCard';

    record_name(_) -> error(badarg).
    
    -spec functions(_) -> no_return().

functions(_) -> error(badarg).

-spec function_info(_,_,_) -> no_return().

function_info(_Service, _Function, _InfoType) -> erlang:error(badarg).
